--- #YAML:1.0
name:               Acme-MUDLike
version:            0.02
abstract:           Hang out inside of your application
author:
    - Scott Walters <scott@slowass.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Devel::Pointer:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
